main: me.guitarxpress.gibcraft.GibCraft
name: GibCraft
version: 1.0.0
author: GuitarXpress
api-version: 1.18
description: A minigame based on Ratz InstaGib and Quake. 
depend: [ProtocolLib]

commands:
   gibcraft:
      aliases: gib
      usage: /<command>